using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Client.Domain.Enums
{
    public enum ClassEnum : uint
    {
        None = 255,
		HumanFighter = 0,
		Warrior,
		Gladiator,
		Warlord,
		HumanKnight,
		Paladin,
		DarkAvenger,
		Rogue,
		TreasureHunter,
		Hawkeye,
		HumanMystic,
		HumanWizard,
		Sorceror,
		Necromancer,
		Warlock,
		Cleric,
		Bishop,
		Prophet,
		ElvenFighter,
		ElvenKnight,
		TempleKnight,
		Swordsinger,
		ElvenScout,
		PlainsWalker,
		SilverRanger,
		ElvenMystic,
		ElvenWizard,
		Spellsinger,
		ElementalSummoner,
		ElvenOracle,
		ElvenElder,
		DarkElvenFighter,
		PalusKnight,
		ShillienKnight,
		Bladedancer,
		Assassin,
		AbyssWalker,
		PhantomRanger,
		DarkElvenMystic,
		DarkElvenWizard,
		Spellhowler,
		PhantomSummoner,
		ShillienOracle,
		ShillienElder,
		OrcFighter,
		OrcRaider,
		Destroyer,
		OrcMonk,
		Tyrant,
		OrcMystic,
		OrcShaman,
		Overlord,
		Warcryer,
		DwarvenFighter,
		DwarvenScavenger,
		BountyHunter,
		DwarvenArtisan,
		Warsmith,
		Duelist = 88,
		Dreadnought,
		PhoenixKnight,
		HellKnight,
		Sagittarius,
		Adventurer,
		Archmage,
		Soultaker,
		ArcanaLord,
		Cardinal,
		Hierophant,
		EvaTemplar,
		SwordMuse,
		WindRider,
		MoonlightSentinel,
		MysticMuse,
		ElementalMaster,
		EvaSaint,
		ShillienTemplar,
		SpectralDancer,
		GhostHunter,
		GhostSentinel,
		StormScreamer,
		SpectralMaster,
		ShillienSaint,
		Titan,
		GrandKhauatari,
		Dominator,
		Doomcryer,
		FortuneSeeker,
		Maestro
    }
}
